autoInstallPeers: true

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver

overrides:
  jiti: <2.2.0

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: true
