autoInstallPeers: true

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - '@swc/core'
  - simple-git-hooks

overrides:
  jiti: <2.2.0

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: true
