autoInstallPeers: true

ignoreWorkspaceRootCheck: true

allowBuilds:
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: true

minimumReleaseAgeExclude:
  - '@bfra.me/eslint-config@0.51.2'
  - '@bfra.me/prettier-config@0.16.10 || 0.16.11'
