---
# Renovate this repository if Renovate-specific tasks are checked or if dispatched.
name: Renovate

'on':
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches: ['**']
  workflow_dispatch:
    inputs:
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false

jobs:
  renovate:
    name: Renovate
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/renovate.yaml@d412d166ee433bd627c1985384b016603f1c1a78 # v1.12.1
    with:
      print_config: ${{ inputs.print_config || false }}
