---
# Renovate this repository if Renovate-specific tasks are checked or if dispatched.
name: Renovate

on:
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches: ['**']
  workflow_dispatch:
    inputs:
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false

jobs:
  renovate:
    name: Renovate
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/renovate.yaml@cda73cc24af8385f6cd25e22fa5b3647bbad162f # v2.5.2
    with:
      print_config: ${{ inputs.print_config || false }}
