name: Update `dist/`
on:
  pull_request_target:
    types: [labeled, synchronize]

jobs:
  update-dist:
    name: Update `dist/`
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Get Workflow Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}
          permissions: >
            contents:write

      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Setup Node.js $${ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        env:
          NODE_VERSION: 18.x # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build, commit, and push the `dist/` directory
        run: |
          yarn build
          if [[ $(git status -s -- dist/ | wc -l) -gt 0 ]]; then
            git config --local user.email '118100583+bfra-me[bot]@users.noreply.github.com'
            git config --local user.name 'bfra-me[bot]'
            git add dist/
            git commit -m 'chore: update the contents of the `dist/` directory'
            git push origin HEAD
          fi
