# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

on:
  push:
    branches: [main]
  schedule:
    - cron: '15 16 * * *' # Every day at 16:15 UTC
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@058b81211bf35133c2988de1619be09a2158fbd6 # v4.16.37
