# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

on:
  push:
    branches: [main]
  schedule:
    - cron: '15 16 * * *' # Every day at 16:15 UTC
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@dd6ab96816fe70f28628856e72ef2543b16b0946 # v4.16.26
