# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

on:
  push:
    branches: [main]
  schedule:
    - cron: '15 16 * * *' # Every day at 16:15 UTC
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@5fc9776c379f20bfdee2c8982699faf8f0059f29 # v4.16.36
